### ISSUE TITLE
mac compiling but not running

### ISSUE THREAD

**Issue by gedw99** [mothfuzz/letsgo#1]
Cool lib. Nice and simple clean. 

Getting the same error on 2 examples.

get the SDL binaries for Mac.
```
brew install sdl2{,_image,_mixer,_ttf,_gfx} pkg-config 
```

``` 
raycasting git:(main) ✗ ./raycasting 
panic: Could not initialize OpenGL / GLES library

goroutine 1 [running, locked to thread]:
github.com/mothfuzz/letsgo/app.Init()
	/Users/apple/workspace/go/src/github.com/mothfuzz/letsgo/app/app.go:56 +0x3e5
main.main()
	/Users/apple/workspace/go/src/github.com/mothfuzz/letsgo/examples/raycasting/main.go:79 +0x75
➜  raycasting git:(main) ✗ cd ..
➜  examples git:(main) ✗ ls 
audio        boundingbox  camera_actor messaging    raycasting
➜  examples git:(main) ✗ cd audio 
➜  audio git:(main) ✗ go build .
➜  audio git:(main) ✗ ls
audio     main.go   resources
➜  audio git:(main) ✗ ./audio 
panic: Could not initialize OpenGL / GLES library

goroutine 1 [running, locked to thread]:
github.com/mothfuzz/letsgo/app.Init()
	/Users/apple/workspace/go/src/github.com/mothfuzz/letsgo/app/app.go:56 +0x3e5
main.main()
	/Users/apple/workspace/go/src/github.com/mothfuzz/letsgo/examples/audio/main.go:26 +0x65
```

**Comment by mothfuzz** [comment]
Just pushed fea3c3b which I believe should fix the issues. I don't have a mac to test on, but I think it should work.

**Comment by gedw99** [comment]
Their opengl3 example did not work so well... Builds but not screen output.

``` 
➜  examples git:(master) ✗ cd opengl3 
➜  opengl3 git:(master) ✗ go build .
go: cannot find main module, but found .git/config in /Users/apple/workspace/go/src/github.com/veandco/go-sdl2-examples
	to create a module there, run:
	cd ../.. && go mod init
➜  opengl3 git:(master) ✗ go mod init
go: creating new go.mod: module github.com/veandco/go-sdl2-examples/examples/opengl3
go: to add module requirements and sums:
	go mod tidy
➜  opengl3 git:(master) ✗ go mod tidy
go: finding module for package github.com/chsc/gogl/gl33
go: finding module for package github.com/veandco/go-sdl2/sdl
go: downloading github.com/chsc/gogl v0.0.0-20131111203533-c411acc846b6
go: found github.com/chsc/gogl/gl33 in github.com/chsc/gogl v0.0.0-20131111203533-c411acc846b6
go: found github.com/veandco/go-sdl2/sdl in github.com/veandco/go-sdl2 v0.4.20
➜  opengl3 git:(master) ✗ go build .
➜  opengl3 git:(master) ✗ ls
go.mod     go.sum     opengl3    opengl3.go
➜  opengl3 git:(master) ✗ ./opengl3 
Compiled Vertex Shader: 0
Compiled Fragment Shader: 0
Program Link: 0
Uniform Link: 0
[1720ms]MouseMotion	id:0	x:83	y:135	xrel:0	yrel:0
[1777ms]MouseMotion	id:0	x:131	y:88	xrel:48	yrel:-47
[1994ms]MouseMotion	id:0	x:182	y:14	xrel:51	yrel:-74
[2046ms]MouseMotion	id:0	x:197	y:7	xrel:15	yrel:-7
[2100ms]MouseMotion	id:0	x:200	y:7	xrel:3	yrel:0
[2260ms]MouseMotion	id:0	x:200	y:6	xrel:0	yrel:-1
[2312ms]MouseMotion	id:0	x:201	y:5	xrel:1	yrel:-1
[2375ms]MouseMotion	id:0	x:205	y:0	xrel:4	yrel:-8
[4827ms]MouseMotion	id:0	x:207	y:29	xrel:0	yrel:0
[4880ms]MouseMotion	id:0	x:207	y:109	xrel:0	yrel:80
[4935ms]MouseMotion	id:0	x:207	y:126	xrel:0	yrel:17
[4993ms]MouseMotion	id:0	x:207	y:137	xrel:0	yrel:11
[5056ms]MouseMotion	id:0	x:207	y:156	xrel:0	yrel:19
[5110ms]MouseMotion	id:0	x:208	y:163	xrel:1	yrel:7
[5112ms]MouseMotion	id:0	x:209	y:165	xrel:1	yrel:2
[5165ms]MouseMotion	id:0	x:221	y:188	xrel:12	yrel:23
[5221ms]MouseMotion	id:0	x:242	y:210	xrel:21	yrel:22
[5275ms]MouseMotion	id:0	x:270	y:213	xrel:28	yrel:3
[5332ms]MouseMotion	id:0	x:275	y:211	xrel:5	yrel:-2
[5595ms]MouseMotion	id:0	x:248	y:213	xrel:-27	yrel:2
[5649ms]MouseMotion	id:0	x:211	y:241	xrel:-37	yrel:28
[5703ms]MouseMotion	id:0	x:196	y:248	xrel:-15	yrel:7
[5758ms]MouseMotion	id:0	x:193	y:249	xrel:-3	yrel:1
[5811ms]MouseMotion	id:0	x:221	y:212	xrel:28	yrel:-37
[5866ms]MouseMotion	id:0	x:269	y:185	xrel:48	yrel:-27
[5919ms]MouseMotion	id:0	x:276	y:200	xrel:7	yrel:15
[5974ms]MouseMotion	id:0	x:239	y:235	xrel:-37	yrel:35
[6029ms]MouseMotion	id:0	x:234	y:238	xrel:-5	yrel:3
[6086ms]MouseMotion	id:0	x:261	y:226	xrel:27	yrel:-12
[6138ms]MouseMotion	id:0	x:257	y:233	xrel:-4	yrel:7
[6191ms]MouseMotion	id:0	x:256	y:234	xrel:-1	yrel:1
[6624ms]MouseMotion	id:0	x:252	y:192	xrel:-4	yrel:-42
[6679ms]MouseMotion	id:0	x:251	y:90	xrel:-1	yrel:-102
[6735ms]MouseMotion	id:0	x:255	y:41	xrel:4	yrel:-49
[6787ms]MouseMotion	id:0	x:254	y:31	xrel:-1	yrel:-10
[6842ms]MouseMotion	id:0	x:250	y:27	xrel:-4	yrel:-4
[6843ms]MouseMotion	id:0	x:249	y:26	xrel:-1	yrel:-1
[6900ms]MouseMotion	id:0	x:243	y:18	xrel:-6	yrel:-8
[6955ms]MouseMotion	id:0	x:238	y:11	xrel:-5	yrel:-7
[7008ms]MouseMotion	id:0	x:235	y:7	xrel:-3	yrel:-4
[7069ms]MouseMotion	id:0	x:227	y:0	xrel:-8	yrel:-10
[11592ms]MouseMotion	id:0	x:53	y:288	xrel:0	yrel:0
[11645ms]MouseMotion	id:0	x:156	y:203	xrel:103	yrel:-85
[11834ms]MouseMotion	id:0	x:170	y:178	xrel:14	yrel:-25
[11888ms]MouseMotion	id:0	x:196	y:151	xrel:26	yrel:-27
[11940ms]MouseMotion	id:0	x:205	y:108	xrel:9	yrel:-43
[11995ms]MouseMotion	id:0	x:199	y:70	xrel:-6	yrel:-38
[12054ms]MouseMotion	id:0	x:196	y:63	xrel:-3	yrel:-7
[12109ms]MouseMotion	id:0	x:187	y:28	xrel:-9	yrel:-35
[12163ms]MouseMotion	id:0	x:182	y:12	xrel:-5	yrel:-16
[12215ms]MouseMotion	id:0	x:182	y:8	xrel:0	yrel:-4
[12430ms]MouseMotion	id:0	x:181	y:0	xrel:-1	yrel:-30
[14668ms]MouseMotion	id:0	x:207	y:136	xrel:0	yrel:0
[14725ms]MouseMotion	id:0	x:223	y:386	xrel:16	yrel:250
[14933ms]MouseMotion	id:0	x:220	y:423	xrel:-3	yrel:37
[14986ms]MouseMotion	id:0	x:213	y:456	xrel:-7	yrel:33
[15039ms]MouseMotion	id:0	x:210	y:467	xrel:-3	yrel:11
[15093ms]MouseMotion	id:0	x:210	y:468	xrel:0	yrel:1
[15145ms]MouseMotion	id:0	x:209	y:468	xrel:-1	yrel:0
[15198ms]MouseMotion	id:0	x:209	y:467	xrel:0	yrel:-1
[15251ms]MouseMotion	id:0	x:209	y:460	xrel:0	yrel:-7
[15306ms]MouseMotion	id:0	x:210	y:439	xrel:1	yrel:-21
[15361ms]MouseMotion	id:0	x:215	y:427	xrel:5	yrel:-12
[39622ms]MouseMotion	id:0	x:215	y:427	xrel:0	yrel:0
[43986ms]MouseMotion	id:0	x:225	y:351	xrel:10	yrel:-76
[44697ms]MouseMotion	id:0	x:176	y:256	xrel:-49	yrel:-95
[44750ms]MouseMotion	id:0	x:89	y:48	xrel:-87	yrel:-208
[44802ms]MouseMotion	id:0	x:73	y:2	xrel:-16	yrel:-46
[44959ms]MouseMotion	id:0	x:67	y:0	xrel:-6	yrel:-3
➜  opengl3 git:(master) ✗ 

```

Runs but windows contents are black. It uses a weird opengl lib so maybe thats it. 

![Screenshot 2022-04-11 at 11 56 17](https://user-images.githubusercontent.com/53147028/162714591-02b008bb-2e8a-4a1c-8541-ce8f5efda50b.png)

**Comment by mothfuzz** [comment]
Very interesting... the panic when trying to use `glBindImageTexture` would make sense since that's OpenGL 4.2+ functionality and macs only support up to 4.1. But the library is using GL 3.1, and isn't even calling glBindImageTexture anywhere in the first place. I'll check and make sure the right dependencies are being used.
